on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - uses: actions/checkout@master

      # install dependencies, build, and test
      - name: install, build, and test
        run: |
          yarn
          yarn test
   do_deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        # checkout the repo
        - uses: actions/checkout@master

        # install dependencies, build, and test
        - name: install and build
          run: |
            yarn

        # deploy web app using publish profile credentials
        - uses: azure/appservice-actions/webapp@master
          with:
            app-name: shipit-bot
            publish-profile: ${{ secrets.azureWebAppPublishProfile }}
 
